/* DB MODEL
- id
- kenteken
- merk
- model
- uitvoering
- bouwjaar
- brandstof
- kilometerstand
- prijs
- foto's
- verkoper_id
- datum
- transmissie
- carosserie
- vermogen (pk)
- vermogen (kw) (Dit komt terug uit de RDW brandstof dataset, kan omgerekend worden naar PK door het te vermenigvuldigen met 1.35962)
- koppel (nm)
- cilinderinhoud
- aantal cilinders
- aandrijving
- versnellingen
- topsnelheid
- acceleratie (0-100)
- gewicht
- aantal zitplaatsen
- aantal deuren
- kleur
- APK
- trekmassa geremd
- trekmassa ongeremd
- max massa
- max massa samenstelling
- energieklasse
- verbruik stad
- verbruik snelweg
- verbruik gecombineerd
- co2 uitstoot (g/km)
*/